name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16.10.0
          architecture: x64
      - name: Update npm
        run: npm install -g npm
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependency
        run: yarn install
      - name: Build
        run: yarn build
